import type { SketchDoc } from "@sketchcoder/graph";
import { file, labelOf, slug, type PatternMatch, type ScaffoldResult } from "./types";

export function buildRag(doc: SketchDoc, match: PatternMatch): ScaffoldResult {
  const store = labelOf(match.slots.store, "Vector store");
  const model = labelOf(match.slots.model, "Grounded LLM");
  const api = labelOf(match.slots.api, "Ask API");
  const client = labelOf(match.slots.client, "Chat UI");
  const embed = labelOf(match.slots.embed, "Embedder");
  const retriever = labelOf(match.slots.retriever, "Retriever");
  const source = labelOf(match.slots.source, "Document corpus");
  const pkg = slug(doc.intent || "rag-citations");

  const files = [
    file("README.md", [
      `# ${pkg}`,
      "",
      "Scaffolded by SketchCoder from a system sketch.",
      "",
      `**Intent:** ${doc.intent || "RAG with citations"}`,
      "",
      "## Topology",
      "",
      `- ${source} → ${embed} → ${store}`,
      `- ${client} → ${api} → ${retriever} → ${model}`,
      "",
      "## Run",
      "",
      "```bash",
      "cp .env.example .env",
      "npm install",
      "npm run ingest -- ./docs",
      "npm run dev",
      "```",
      "",
      "Ingest writes `data/index.json` so the server can load chunks after restart.",
      "",
      "POST `/api/ask` with `{ \"query\": \"...\" }` and stream cited answers.",
    ]),
    file("package.json", [
      `{`,
      `  "name": "${pkg}",`,
      `  "private": true,`,
      `  "type": "module",`,
      `  "scripts": {`,
      `    "dev": "tsx watch src/server.ts",`,
      `    "ingest": "tsx src/ingest.ts",`,
      `    "start": "tsx src/server.ts"`,
      `  },`,
      `  "dependencies": {`,
      `    "openai": "^4.77.0"`,
      `  },`,
      `  "devDependencies": {`,
      `    "tsx": "^4.19.2",`,
      `    "typescript": "^5.7.3"`,
      `  }`,
      `}`,
    ]),
    file(".env.example", [
      "OPENAI_API_KEY=",
      "OPENAI_MODEL=gpt-4o-mini",
      "EMBEDDING_MODEL=text-embedding-3-small",
      "TOP_K=6",
    ]),
    file("src/types.ts", [
      "export type Citation = {",
      "  id: string;",
      "  source: string;",
      "  excerpt: string;",
      "  score: number;",
      "};",
      "",
      "export type Chunk = {",
      "  id: string;",
      "  source: string;",
      "  text: string;",
      "  embedding: number[];",
      "};",
      "",
      "export type AskEvent =",
      "  | { type: \"citations\"; citations: Citation[] }",
      "  | { type: \"token\"; text: string }",
      "  | { type: \"done\" };",
    ]),
    file("src/lib/chunk.ts", [
      `/** ${source} — split files into overlapping passages. */`,
      "export function chunkText(text: string, source: string, size = 800, overlap = 120) {",
      "  const chunks: { id: string; source: string; text: string }[] = [];",
      "  let i = 0;",
      "  let n = 0;",
      "  while (i < text.length) {",
      "    const slice = text.slice(i, i + size).trim();",
      "    if (slice) chunks.push({ id: `${source}-${n++}`, source, text: slice });",
      "    i += size - overlap;",
      "  }",
      "  return chunks;",
      "}",
    ]),
    file("src/lib/embedder.ts", [
      `/** ${embed} — turn passages into vectors. */`,
      "import OpenAI from \"openai\";",
      "",
      "const client = new OpenAI();",
      "",
      "export async function embed(texts: string[]): Promise<number[][]> {",
      "  const model = process.env.EMBEDDING_MODEL ?? \"text-embedding-3-small\";",
      "  const res = await client.embeddings.create({ model, input: texts });",
      "  return res.data.map((d) => d.embedding);",
      "}",
    ]),
    file("src/lib/store.ts", [
      `/** ${store} — file-backed vector index so ingest survives into the server. */`,
      "import { readFileSync, writeFileSync, mkdirSync, existsSync } from \"node:fs\";",
      "import { dirname, join } from \"node:path\";",
      "import { fileURLToPath } from \"node:url\";",
      "import type { Chunk } from \"../types\";",
      "",
      "const root = join(dirname(fileURLToPath(import.meta.url)), \"..\", \"..\", \"data\");",
      "const indexPath = join(root, \"index.json\");",
      "",
      "function load(): Chunk[] {",
      "  try {",
      "    if (!existsSync(indexPath)) return [];",
      "    return JSON.parse(readFileSync(indexPath, \"utf8\")) as Chunk[];",
      "  } catch {",
      "    return [];",
      "  }",
      "}",
      "",
      "function save(chunks: Chunk[]) {",
      "  mkdirSync(root, { recursive: true });",
      "  writeFileSync(indexPath, JSON.stringify(chunks));",
      "}",
      "",
      "export function upsert(batch: Chunk[]) {",
      "  const chunks = load();",
      "  chunks.push(...batch);",
      "  save(chunks);",
      "}",
      "",
      "export function all(): Chunk[] {",
      "  return load();",
      "}",
      "",
      "function cosine(a: number[], b: number[]) {",
      "  let dot = 0;",
      "  let na = 0;",
      "  let nb = 0;",
      "  for (let i = 0; i < a.length; i++) {",
      "    dot += a[i] * b[i];",
      "    na += a[i] * a[i];",
      "    nb += b[i] * b[i];",
      "  }",
      "  return dot / (Math.sqrt(na) * Math.sqrt(nb) + 1e-8);",
      "}",
      "",
      "export function query(vector: number[], k = 6): Chunk[] {",
      "  const chunks = load();",
      "  return [...chunks]",
      "    .map((c) => ({ c, score: cosine(vector, c.embedding) }))",
      "    .sort((a, b) => b.score - a.score)",
      "    .slice(0, k)",
      "    .map((x) => x.c);",
      "}",
    ]),
    file("src/lib/retriever.ts", [
      `/** ${retriever} — top-k with citation payloads. */`,
      "import { embed } from \"./embedder\";",
      "import { query } from \"./store\";",
      "import type { Citation } from \"../types\";",
      "",
      "export async function retrieve(question: string, k = Number(process.env.TOP_K ?? 6)) {",
      "  const [vector] = await embed([question]);",
      "  const hits = query(vector, k);",
      "  const citations: Citation[] = hits.map((h, i) => ({",
      "    id: String(i + 1),",
      "    source: h.source,",
      "    excerpt: h.text.slice(0, 280),",
      "    score: 0,",
      "  }));",
      "  return { hits, citations };",
      "}",
    ]),
    file("src/lib/llm.ts", [
      `/** ${model} — answer only from retrieved context. */`,
      "import OpenAI from \"openai\";",
      "import type { Citation } from \"../types\";",
      "",
      "const client = new OpenAI();",
      "",
      "export async function* ground(question: string, citations: Citation[]) {",
      "  const context = citations",
      "    .map((c) => `[${c.id}] ${c.source}\\n${c.excerpt}`)",
      "    .join(\"\\n\\n\");",
      "  const stream = await client.chat.completions.create({",
      "    model: process.env.OPENAI_MODEL ?? \"gpt-4o-mini\",",
      "    stream: true,",
      "    messages: [",
      "      {",
      "        role: \"system\",",
      "        content:",
      "          \"Answer using only the numbered sources. Cite like [1]. If the sources are silent, say you do not know.\",",
      "      },",
      "      { role: \"user\", content: `Sources:\\n${context}\\n\\nQuestion: ${question}` },",
      "    ],",
      "  });",
      "  for await (const part of stream) {",
      "    const text = part.choices[0]?.delta?.content;",
      "    if (text) yield text;",
      "  }",
      "}",
    ]),
    file("src/ingest.ts", [
      `/** Ingest ${source} from a folder of .md / .txt files. */`,
      "import { readdir, readFile } from \"node:fs/promises\";",
      "import { join } from \"node:path\";",
      "import { chunkText } from \"./lib/chunk\";",
      "import { embed } from \"./lib/embedder\";",
      "import { upsert } from \"./lib/store\";",
      "",
      "const dir = process.argv[2] ?? \"./docs\";",
      "",
      "async function main() {",
      "  const names = await readdir(dir);",
      "  for (const name of names) {",
      "    if (!/\\.(md|txt)$/i.test(name)) continue;",
      "    const raw = await readFile(join(dir, name), \"utf8\");",
      "    const pieces = chunkText(raw, name);",
      "    const vectors = await embed(pieces.map((p) => p.text));",
      "    upsert(pieces.map((p, i) => ({ ...p, embedding: vectors[i] })));",
      "    console.log(`indexed ${name} (${pieces.length} chunks)`);",
      "  }",
      "}",
      "",
      "main();",
    ]),
    file("src/server.ts", [
      `/** ${api} — stream cited answers. */`,
      "import { createServer } from \"node:http\";",
      "import { retrieve } from \"./lib/retriever\";",
      "import { ground } from \"./lib/llm\";",
      "",
      "const server = createServer(async (req, res) => {",
      "  if (req.method === \"GET\" && req.url === \"/\") {",
      "    res.setHeader(\"content-type\", \"text/html; charset=utf-8\");",
      "    res.end(html());",
      "    return;",
      "  }",
      "  if (req.method === \"POST\" && req.url === \"/api/ask\") {",
      "    const body = await readBody(req);",
      "    const query = JSON.parse(body).query as string;",
      "    const { citations } = await retrieve(query);",
      "    res.writeHead(200, {",
      "      \"content-type\": \"text/event-stream\",",
      "      \"cache-control\": \"no-cache\",",
      "    });",
      "    res.write(`data: ${JSON.stringify({ type: \"citations\", citations })}\\n\\n`);",
      "    for await (const text of ground(query, citations)) {",
      "      res.write(`data: ${JSON.stringify({ type: \"token\", text })}\\n\\n`);",
      "    }",
      "    res.end(`data: ${JSON.stringify({ type: \"done\" })}\\n\\n`);",
      "    return;",
      "  }",
      "  res.statusCode = 404;",
      "  res.end(\"not found\");",
      "});",
      "",
      "function readBody(req: import(\"node:http\").IncomingMessage) {",
      "  return new Promise<string>((resolve) => {",
      "    const chunks: Buffer[] = [];",
      "    req.on(\"data\", (c) => chunks.push(c));",
      "    req.on(\"end\", () => resolve(Buffer.concat(chunks).toString(\"utf8\")));",
      "  });",
      "}",
      "",
      `function html() {`,
      "  return `<!doctype html>",
      `<meta charset=\"utf-8\" />`,
      `<title>${client}</title>`,
      `<style>`,
      "  body { font: 16px/1.5 ui-sans-serif, system-ui; max-width: 640px; margin: 12vh auto; color: #111; }",
      "  h1 { font-weight: 550; letter-spacing: -0.03em; }",
      "  textarea { width: 100%; min-height: 80px; }",
      "  #cites { font-size: 13px; color: #444; }",
      "</style>",
      `<h1>${client}</h1>`,
      `<p>Ask the corpus. Answers arrive with citations.</p>`,
      `<textarea id=\"q\" placeholder=\"What does the handbook say about on-call?\"></textarea>`,
      `<p><button id=\"go\">Ask</button></p>`,
      `<pre id=\"out\"></pre>`,
      `<div id=\"cites\"></div>`,
      `<script>`,
      "  go.onclick = async () => {",
      "    out.textContent = \"\";",
      "    cites.textContent = \"\";",
      "    const res = await fetch(\"/api/ask\", {",
      "      method: \"POST\",",
      "      headers: { \"content-type\": \"application/json\" },",
      "      body: JSON.stringify({ query: q.value }),",
      "    });",
      "    const reader = res.body.getReader();",
      "    const dec = new TextDecoder();",
      "    let buf = \"\";",
      "    while (true) {",
      "      const { done, value } = await reader.read();",
      "      if (done) break;",
      "      buf += dec.decode(value, { stream: true });",
      "      const parts = buf.split(\"\\n\\n\");",
      "      buf = parts.pop();",
      "      for (const p of parts) {",
      "        if (!p.startsWith(\"data: \")) continue;",
      "        const ev = JSON.parse(p.slice(6));",
      "        if (ev.type === \"token\") out.textContent += ev.text;",
      "        if (ev.type === \"citations\") cites.textContent = ev.citations.map(c => `[${c.id}] ${c.source}`).join(\" · \");",
      "      }",
      "    }",
      "  };",
      "</script>`;",
      "}",
      "",
      "server.listen(3000, () => console.log(\"ask api on http://localhost:3000\"));",
    ]),
    file("docs/sample.md", [
      "# Handbook",
      "",
      "On-call engineers rotate weekly. Severity-1 incidents page the primary within five minutes.",
      "Post-incident reviews are due within two business days and must include a customer-facing summary.",
    ]),
  ];

  const nodeFiles: Record<string, string[]> = {};
  if (match.slots.source) nodeFiles[match.slots.source.id] = ["src/lib/chunk.ts", "src/ingest.ts"];
  if (match.slots.embed) nodeFiles[match.slots.embed.id] = ["src/lib/embedder.ts"];
  if (match.slots.store) nodeFiles[match.slots.store.id] = ["src/lib/store.ts"];
  if (match.slots.retriever) nodeFiles[match.slots.retriever.id] = ["src/lib/retriever.ts"];
  if (match.slots.model) nodeFiles[match.slots.model.id] = ["src/lib/llm.ts"];
  if (match.slots.api) nodeFiles[match.slots.api.id] = ["src/server.ts"];
  if (match.slots.client) nodeFiles[match.slots.client.id] = ["src/server.ts"];

  return {
    pattern: "rag",
    summary: `RAG scaffold: ${source} is chunked by ${embed}, indexed in ${store}, retrieved, then grounded through ${model} via ${api}.`,
    nextSteps: [
      "Add real documents under docs/ and run npm run ingest.",
      "Swap the file index for pgvector when you outgrow the demo.",
      "Tighten citation formatting in src/lib/llm.ts.",
    ],
    files,
    nodeFiles,
  };
}
